[tool.poetry]
name = "helper-scripts"
version = "0.1.0"
description = ""
authors = ["mathatan <mathatan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
pyyaml = "^6.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
